matching_groups:
  - /api/courses/.+/classes/.+/assignments/scores
  - /api/courses/.+/classes/.+/assignments/export
  - /api/courses/.+/classes/.+/assignments
  - /api/courses/.+/classes
  - /api/courses/.+/status
  - /api/announcements/.+
  - /api/courses/.+
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
file: /var/log/nginx/access.ndjson
